### ISSUE TITLE
tau value

### ISSUE THREAD

**Issue by summer-lemon** [apcamargo/tspex#10]
Hello, I would like to ask a few questions:
(1) When I calculate tau value, how many columns of values do I need at least?
(2) Can I use it to calculate time specific gene?
(3) Can I use it to calculate specific regulatory elements?
Thank you very much!

**Comment by apcamargo** [comment]
Hi @summer-lemon,
(1) The minimum is 2 (computing specificity with less than that wouldn't make sense), but you can have as much as you want. I'd say that, usually, the more the better, but it depends on your biological question.
(2) Yes. You can use to compute any sort of specificity.
(3) Sure!

**Comment by summer-lemon** [comment]
Thank you very much!
I have another question:
When I calculate the tau value and there are biological replicates, can I input the file in a format where each biological replicate is a column:
gene_ID	treat_rep1	treat_rep2	treat_rep3	control_rep1	control_rep2	control_rep3
A	10	8	8	25	24	23

**Comment by apcamargo** [comment]
Depends on what you are trying to answer. `tspex` doesn't take replicate information into account, so if you have multiple samples for a single tissue (or time point) you would need to aggregate them beforehand (average, median, etc.)

**Comment by summer-lemon** [comment]
Ok, thank you so much!

**Comment by apcamargo** [comment]
You're welcome!
