### ISSUE TITLE
'Negative expression values are not allowed' Error when using already log transformed data

### ISSUE THREAD

**Issue by mgrantpeters** [apcamargo/tspex#14]
Hello, 

This is more of a question than an issue -  I am using your recommended code for assessing specificity in data which has already been log transformed:

`tspex --log bucket_medians.csv tspex_spm.ysv spm`

but I receive the following error: 

`ValueError('Negative expression values are not allowed.')`

If the data is already log transformed, then would negative values not be expected? Should this error not only be used if --log is set to True?

**Comment by apcamargo** [comment]
`tspex` uses log(expression + 1) to prevent negative values. Did you added 1 to the values before applying log?

**Comment by mgrantpeters** [comment]
Thank you for the quick response - I will do this. Great package by the way, other than this question it was seamless to install and use!
